import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./env.css";
import { ThemeProvider } from "@/context/ThemeMode";
import Theme from "@/config/Theme";
import { Suspense } from "react";
import Loading from "@/config/Loading";
import ProviderRedux from "@/redux/Provider";
import ScrollHandle from "@/redux/ScrollHandle";
import { LoginProvider } from "@/context/LoginContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} pb-28`}>
        <ProviderRedux>
          <LoginProvider>
            <ThemeProvider>
              <ScrollHandle />
              <Suspense fallback={<Loading />}>{children}</Suspense>
              <Theme />
            </ThemeProvider>
          </LoginProvider>
        </ProviderRedux>
      </body>
    </html>
  );
}
